<?php

/** APP CONFIGURATION
 */
define("URL", "telegram_bot_url");
//define("BASE_PATH", "path_to_installation_dir");
define("APPLICATION_ROOT_DIR", "application");
define("CORE_APPLICATION_DIR", "appcoree");
define("CORE_CONFIGURATION_DIR", "confige");
define("CORE_FUNCTION_DIR", "functione");
define("CORE_CONTROLLER_DIR", "controllere");
define("CORE_LIBRARIES_DIR", "libre");
define("CONTROLLER_DIR", "controller");
define("MODEL_DIR", "model");
define("TEMPLATE_DIR", "template");
define("LIBRARIES_DIR", "libraries");
define("LOGGER_DIR", "looooggggeeeers");
define("LOGGER_PREFIX_NAME", "loooog");
define("LOGGER_EXTENTION_FILE", "logger");
define("LOGGER_DATE_FORMAT", "Ymd");
/** logger ==> <LOGGER_BASE_PATH>/<LOGGER_PREFIX_NAME>__<LOGGER_DATE_FORMAT>.<LOGGER_EXT_FILE>*
 **
 **
 */

/** DO NOT CHANGE THIS DEFINITONS AND DEFAULT DIRECTORY TREE! YOU CAN CHANGE THE DIR NAME TO MAKE IT */
if (!defined("BASE_PATH")) define("BASE_PATH", __DIR__.DIRECTORY_SEPARATOR);
define("APPLICATION_ROOT_PATH", BASE_PATH.APPLICATION_ROOT_DIR.DIRECTORY_SEPARATOR);
define("CORE_APPLICATION_PATH", APPLICATION_ROOT_PATH.CORE_APPLICATION_DIR.DIRECTORY_SEPARATOR);
define("CORE_CONFIGURATION_PATH", CORE_APPLICATION_PATH.CORE_CONFIGURATION_DIR.DIRECTORY_SEPARATOR);
define("CORE_FUNCTION_PATH", CORE_APPLICATION_PATH.CORE_FUNCTION_DIR.DIRECTORY_SEPARATOR);
define("CORE_CONTROLLER_PATH", CORE_APPLICATION_PATH.CORE_CONTROLLER_DIR.DIRECTORY_SEPARATOR);
define("CORE_LIBRARIES_PATH", CORE_APPLICATION_PATH.CORE_LIBRARIES_DIR.DIRECTORY_SEPARATOR);
define("CONTROLLER_PATH", APPLICATION_ROOT_PATH.CONTROLLER_DIR.DIRECTORY_SEPARATOR);
define("LIBRARIES_PATH", APPLICATION_ROOT_PATH.LIBRARIES_DIR.DIRECTORY_SEPARATOR);
define("TEMPLATE_PATH", APPLICATION_ROOT_PATH.TEMPLATE_DIR.DIRECTORY_SEPARATOR);
define("MODEL_PATH", APPLICATION_ROOT_PATH.MODEL_DIR.DIRECTORY_SEPARATOR);
define("LOGGER_PATH", APPLICATION_ROOT_PATH.LOGGER_DIR.DIRECTORY_SEPARATOR);

/** BOOTSTRAP
 */
include APPLICATION_ROOT_PATH."Main.php";
/** APP START */
?>